### PR TITLE
Monitor filestore nfs and fn to get all existing vms

### PR DESCRIPTION
**Pull request by youliangtan**
- Add the option to monitor mounted filestores on the dashboard. (sorted with size from large to small)
Screenshot from 2023-09-26 01-35-44

- Default display all existing TPU vms from all zones

### CODE REVIEW

**Comment by kvablack** [comment]
Thanks, LGTM! Only one change: can we still run with the `--csv vms.csv` mode? I'd rather be able to control what VMs show up, at least for now, rather than showing all of them by default.

**Comment by youliangtan** [comment]
Yes, the `--all_zones` is an optional arg

by default user will either need to use `--csv` or `--all_zones`

**Comment by kvablack** [comment]
Ok, feel free to merge and re-deploy the monitor whenever

**Comment by youliangtan** [comment]
Thanks, would need ur help in merging since i don't have write access. I will redeploy it soon after :+1:

**Pull request merged**
